class AccountSettingsPage{
    navigate(url){
        cy.visit(url)
    }
    OpenAccountSettings(){
        cy.get('[data-test="sidenav-user-settings"]')
        .click()
    }
    FirstName(firstname){
        cy.get('[data-test="user-settings-firstName-input"]')
        .wait(1500)
        .type('{del}{selectall}{backspace}')
        .wait(1500)
        .type(firstname)
    }
    LastName(lastname){
        cy.get('[data-test="user-settings-lastName-input"]')        
        .wait(1500)
        .type('{del}{selectall}{backspace}')
        .wait(1500)
        .type(lastname)
    }
    Email(email){
        cy.get('[data-test="user-settings-email-input"]')      
        .type('{del}{selectall}{backspace}')  
        .wait(1500)
        .type(email)
    }
    PhoneNo(phone){
        cy.get('[data-test="user-settings-phoneNumber-input"]')  
        .type('{del}{selectall}{backspace}')      
        .wait(1500)
        .type(phone)
    }
    Submit(){
        cy.get('[data-test="user-settings-submit"]')
        .wait(1500)
        .click()
    }
}
export default AccountSettingsPage